# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: CI=false npm run build --if-present
        name: React Build
      - id: auth
        name: Load Google auth credentials
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - id: upload-script
        name: Upload install script to CDN
        uses: google-github-actions/upload-cloud-storage@e2673068897289f29bd311609b8ecf0cda0d988c
        with:
          path: install.sh
          destination: dl.techied.me/
          headers: |-
            Cache-Control: no-cache, no-store, must-revalidate
      - id: compress
        name: Compress built files
        run: tar -czf /tmp/latest.tar.gz .
      - id: upload-file
        name: Upload Latest Build to CDN
        uses: google-github-actions/upload-cloud-storage@e2673068897289f29bd311609b8ecf0cda0d988c
        with:
          path: /tmp/latest.tar.gz
          destination: dl.techied.me/
          headers: |-
            Cache-Control: no-cache, no-store, must-revalidate