# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
  upload:
    runs-on: ubuntu-latest
    name: Cloud Storage Uploader
    steps:
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - id: checkout
        uses: actions/checkout@v2
      - id: compress
        run: pwd
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: /path/to/file
          destination: bucket-name/file

      # Example of using the output
      - id: uploaded-files
        uses: foo/bar@master
        env:
          file: ${{steps.upload-file.outputs.uploaded}}
